### ISSUE TITLE
Action Reset Can't be used in Scene inside Drawer

### ISSUE THREAD

**Issue by jepicode** [RNRF/react-native-router-flux#3308]
### Version
- react-native-router-flux v4.0.0-beta.31
- react v16.3.1
- react-native v0.55.3

### Expected behaviour
Action can link to expected scene and reset the stack, so if user pressed back button it will be close.

### Actual behaviour
Action can't find route, because scene inside `<Drawer>`

I placed a scene inside the `<Drawer>`, when I want to link and reset the stack using `ActionConst.reset`, It can't found the route. It said "There is no route defined for key".

Here's my code
```
<Router>
            <Stack
              key="customNavBar"
              hideTabBar
              titleStyle={{ alignSelf: 'center' }}
            >
              <Drawer
                hideNavBar
                key="drawer"
                contentComponent={SideBar} 
                drawerWidth={300}
                drawerOpenRoute="DrawerOpen"
                drawerCloseRoute="DrawerClose"
                drawerToggleRoute="DrawerToggle"
              >
                <Scene key="AHome" hideNavBar component={AHome} />
              </Drawer>
              <Scene type="reset" key="Login" hideNavBar component={Login} initial />
         </Stack>
    </Router>
```

The Login will redirect to AHome, and I don't want user can back to Login if they're logged

**Comment by aksonov** [comment]
betas are not supported, please upgrade to latest (4.0.5) and reopen if any

**Comment by jepicode** [comment]
I have updated to lastest version, and it's still same error occured.

and I can have autoredirect in componentdidmount, I don't know why, but it doesn't work
