### ISSUE TITLE
Can't redirect after upgraded to 4.0.5

### ISSUE THREAD

**Issue by jepicode** [RNRF/react-native-router-flux#3310]
### Version

- react-native-router-flux v4.0.5
- react v16.3.1
- react-native v0.55.3

### Expected behaviour
Actions work to redirect to the another page

### Actual behaviour
Actions doesn't work

I just upgraded my RNRF to 4.0.5, I didn't change my code. But in lastest version the Actions can't be triggered in ComponentDidMount, but it's still work for button.

```
ComponentDidMount() {
    console.log('mounted') // triggered
    Actions.Home(); // didn't triggered
    console.log('test') // triggered
}
```

**Comment by hackpar** [comment]
+1

**Comment by aksonov** [comment]
You have to use `setTimeout` wrapper for next animation.
