### ISSUE TITLE
Component recreate after it is unMounted when I double-click the back button quickly on Android

### ISSUE THREAD

**Issue by EdwardtoGitHub** [RNRF/react-native-router-flux#3321]
### Version
Tell us which versions you are using:

- react-native-router-flux v4.0.3
- react v16.3.1
- react-native v0.55.4

### Expected behaviour
Scene A=>B=>C
A push B, B push C
both A,B,C is component.
now when I click the back button in C, C will invoke Actions.pop(),thus the Scene is B now.
The component C will unmount.Then i click the back button again.The B invokes the Actions.pop(),
The component B will unmount.And the Scene is A now.

### Actual behaviour
The behaviour is normal when i double-click the back button  slowly,
Then lifecycle i watch in the logcat:
C: willUnmountred
B: willUnmountred

but behaviour is innormal when i double-click the back button quickly(in a short time)
the component C is recreated when it isMounted.
Then lifecycle i watch in the logcat:
C: willUnmountred
C: constructor
C: willMount
C: render
B: willUnmountred
C: willUnmountred

###Notice
Except clicking the back button on Android,I also find the issuse happens when i double-click the button quickly
<Button onpress={()=>Acitions.pop()}/>
but behave normally when i only click the button once
 <Button onpress={()=>{Acitions.pop();Actions.pop()}}/>

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1.I also repoduce the issue with the Example the latest react-native-router-flux provides
2.
3.

### Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by EdwardtoGitHub** [comment]
### Reproducible Demo
Code
![login](https://user-images.githubusercontent.com/19811123/47128400-97adb700-d2c3-11e8-828e-b55b4ac0c451.png)
![login2](https://user-images.githubusercontent.com/19811123/47128402-98464d80-d2c3-11e8-9070-c38018324b9f.png)
![login3](https://user-images.githubusercontent.com/19811123/47128434-b57b1c00-d2c3-11e8-89df-fb6114af264a.png)
Log
login => login2 => login3
![image](https://user-images.githubusercontent.com/19811123/47128531-291d2900-d2c4-11e8-92cb-57bae44a72f7.png)
![image](https://user-images.githubusercontent.com/19811123/47128560-4d790580-d2c4-11e8-9d7d-7b1919ac28ca.png)

**Comment by aksonov** [comment]
Please check pure react-navigation examples and try to reproduce this issue there. If it happens there too then the issue not in RNRF, but within react-navigation used by RNRF
