### ISSUE TITLE
Action Doesn't Pass Props!

### ISSUE THREAD

**Issue by MohammadAlderson** [RNRF/react-native-router-flux#3322]
- react-native-router-flux v4.0.5
- react v16.3.1
- react-native "https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz"

when i try pass props from one scene to another scene it doesn't work!
the scene change but props don't pass!
i think it is because of mobX doesn't install as dependencies for react-native-router-flux v4.0.5
cause it works for react-native-router-flux v4.0.0-beta.31!
any ideas?

**Comment by aksonov** [comment]
Please check examples and how it passes props, create reproducible Example with your problem. v4 is based on react-navigation 2.x when 4.beta - on react-navigation v1.5
