### ISSUE TITLE
Why componentWillUnmount() is not triggered when using Actions.sceneKey()

### ISSUE THREAD

**Issue by Ash-faq** [RNRF/react-native-router-flux#3323]
### Version

- react-native-router-flux ^4.0.5
- react 16.3.1
- react-native ^0.55.0

### Expected behaviour
It should trigger the componentWillUnmount() when using Actions.sceneKey() but its not, but when using popTo, replace, reset its triggered and backnavigation is removed.

### Actual behaviour
I need backnavigation button after navigation and need to trigger componentWillUnmount() of current scene using Actions.sceneKey().

in previous project i have used this and worked fine but now iam getting this issue

Help me on this TIA

**Comment by aksonov** [comment]
`componentWillUnmount` will be triggered by `pop`, but not for `push` (action for  `Actions.sceneKey()`)
