### ISSUE TITLE
Drawer issue in RTL

### ISSUE THREAD

**Issue by firdousali86** [RNRF/react-native-router-flux#3324]
In first app run, drawer appears from opposite side, and travels all the way to other side. Tapping it again behaves normally.

"react-native": "^0.55.3"
"react-native-router-flux": "^4.0.1"

_Originally posted by @firdousali86 in https://github.com/RNRF/react-native-router-flux/issues/2764#issuecomment-431244420_

**Comment by aksonov** [comment]
RNRF just re-uses react-navigation drawer (and its config), so please check this issue with pure react-navigation first.
