### ISSUE TITLE
Actions.key(); is not working

### ISSUE THREAD

**Issue by ninechung** [RNRF/react-native-router-flux#3325]
### Version
  "dependencies": {
    "axios": "^0.18.0",
    "react": "16.4.1",
    "react-native": "0.56.0",
    "react-native-router-flux": "^4.0.5",
    "react-redux": "^5.0.7",
    "redux": "^4.0.1",
    "redux-thunk": "^2.3.0"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "babel-preset-react-native": "^5",
    "jest": "23.6.0",
    "react-test-renderer": "16.4.1",
    "remote-redux-devtools": "^0.5.13"
  }

### Expected behaviour
Actions.login();

### Actual behaviour
Actions.login();  // not working..
Actions.uc();  // not working..

![f19e73c2-6747-4d97-a162-7fadbb8b8a9f](https://user-images.githubusercontent.com/15179320/47240022-95f60780-d419-11e8-9f92-d8a5b3aeaea3.png)

**Comment by ninechung** [comment]
`const RouterComponent = () => {

  const navBarStyle = (Platform.OS === 'android') ? styles.navBarAndroid : styles.navBar;

  return (
    <Router
      navigationBarStyle={navBarStyle}
      uriPrefix={prefix}
      titleStyle={styles.navBarTitle}>
      <Overlay key="overlay">
        <Modal key="modal" hideNavBar/* transitionConfig={transitionConfig}*/>
          <Lightbox key="lightbox">
            <Stack key="root" hideNavBar initial="false" titleStyle={{ alignSelf: 'center' }}>
              <Tabs
                key="tabs"
                tabBarPosition="bottom">
                <Scene
                  key="charList"
                  component={ChatList}
                  title="hm"
                  tabBarLabel="讨论"
                  // icon={TabBarIcon}
                />
                <Scene
                  key="uc"
                  component={Home}
                  title="个人中心"
                  // tabBarLabel="个人中心"
                  // icon={TabBarIcon}
                />
              </Tabs>
              <Scene key="login" component={Login} title="登录" />
            </Stack>
          </Lightbox>
        </Modal>
      </Overlay>
    </Router>

  );
};`

**Comment by aksonov** [comment]
Please check example, it works fine. Please create reproducible example (Expo) to demonstrate the issue and re-open then.
