### ISSUE TITLE
how to save screen state like offset scroll across navigation

### ISSUE THREAD

**Issue by ledarky** [RNRF/react-native-router-flux#3327]
hi
i've seen that every time i change a screen, when i'm come back to the previous screen state is reset
i.e the scroll offset is loss, and all states datas
how to conserve this information across navigation
pls: excuse my english please

**Comment by aksonov** [comment]
Check Example, previous screens should preserve their scroll position...
Feel free to demonstrate your issue with our examples and reopen.
